# Generated by Django 5.0.6 on 2024-06-08 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnettingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=100)),
                ('subnetmask', models.CharField(max_length=100)),
                ('wildcardmask', models.CharField(max_length=100)),
                ('networkbits', models.IntegerField()),
                ('networkadddress', models.CharField(max_length=100)),
                ('first_ip', models.CharField(max_length=100)),
                ('last_ip', models.CharField(max_length=100)),
                ('broadcast_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
