# Generated by Django 5.0.6 on 2024-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnettinghistory',
            name='timecreated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
